services:
  employee-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: employee-api-clean:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    container_name: employee_api_clean