apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      initContainers:
        - name: init-chmod
          image: busybox
          command: ["sh", "-c", "chmod 777 /usr/src/app/database/Employee.db"]
          volumeMounts:
            - name: {{ .Values.volume.database.name }}
              mountPath: {{ .Values.volume.database.containerPath}}
      containers:
        - name: employee-api
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: {{ .Values.volume.database.name }}
              mountPath: {{ .Values.volume.database.containerPath}}
      volumes:
        - name: {{ .Values.volume.database.name }}
          persistentVolumeClaim:
            claimName: employee-api-pvc