apiVersion: v1
kind: PersistentVolume
metadata:
  name: employee-api-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  local:
    path: {{ .Values.volume.database.nodePath}}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - employee-api-worker
